version: '3'
services:
  dev:
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile/Dockerfile
    volumes:
      - ../src/:/app/src/
      - ../dataset/:/app/dataset/
    working_dir:
      /app
    image: jupyter-notebook_python_package
    container_name: JN_python_package
    ports:
      - 8888:8888
    tty: true
    command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''